/**
 * This class is automatically generated by ncg. DO NOT EDIT THIS FILE.
 * This class includes values of some nesC constants from
 * ../common/THPSensorC.h.
 */

public class Constants  {
    public static final short DEFAULT_INTERVAL = 256;
    public static final byte NDATA = 1;
}
